name: dataclasses
description: Wrapper for a dataclass and reflection code generator.
version: 0.0.2
# repository: https://github.com/SimpleTheory/dart-dataclasses

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  collection: ^1.18.0
  ari_utils: ^0.0.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
